// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"database/sql"
)

type Person struct {
	ID        int64          `json:"id"`
	Email     sql.NullString `json:"email"`
	FullName  string         `json:"full_name"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
